# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
# Attention, ça shoot le site mais permet de faire fonctionner les json
fos_rest:
    format_listener:
            rules:
                prefer_extension: false
                fallback_format: json
    routing_loader:
        default_format: json
        include_format: false
    body_listener: true
   # format_listener:
   #       rules:
   #           - { path: '^/', priorities: ['json'], fallback_format: json, prefer_extension: false }
    param_fetcher_listener: true
    access_denied_listener:
        json: true
    view:
        view_response_listener: 'force'
        formats:
            json: true
    zone:
        - { path: ^/api/* }

#fos_rest:
#
#    view:
#        view_response_listener:  true
#
#    exception:
#        exception_controller: 'fos_rest.exception.twig_controller::showAction'
#        codes:
#            Doctrine\ORM\EntityNotFoundException: 404
#
#    format_listener:
#      rules:
#      - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
#
#    body_converter:
#      enabled: true
#
#    zone:
#    - { path: ^/api/* }

