controllers:
    resource: ../../src/Controller/
    type: annotation
#config/routes/annotations.yaml
#Note: use your own resource/directory as you prefer
web_controller:
    resource: ../../src/Controller/
    type: annotation
rest_controller:
    resource: ../../src/Controller/
    type: annotation
    prefix: /api